version: '3.8'

services:
  redis:
    image: 'redis:6.2'
    ports:
      - '6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  mysql:
    image: 'mysql:8.0'
    restart: always
    environment:
      MYSQL_DATABASE: 'farm_db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'